sudo: required
dist: trusty
language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc

before_install:
  - sudo apt-get update && sudo apt-get install build-essential software-properties-common -y && sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update
  - sudo apt-get install gcc-snapshot -y
  - sudo apt-get install gcc-6 g++-6 -y 
  - sudo apt-get install cppcheck
  - sudo apt-get install valgrind
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 60 --slave /usr/bin/g++ g++ /usr/bin/g++-6

install:
  - echo `which $CC`
  - echo `which $CXX`
  - curl https://cmake.org/files/v3.6/cmake-3.6.1-Linux-x86_64.tar.gz | sudo tar -x -z --strip-components 1 -C /usr

script:
  - echo `which $CXX`
  - make lab12_sequential_generator_tests
  - make lab12_teacher_hash_tests
  - make lab12_time_recorder_tests
  - make lab12_tree_preorder_tests
  - make lab12_tree_inorder_tests
  - make lab12_tree_postorder_tests
  


notifications:
  email: false
