sudo: required
dist: trusty
language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc

before_install:
  - sudo apt-get update && sudo apt-get install build-essential software-properties-common -y && sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update
  - sudo apt-get install gcc-snapshot -y
  - sudo apt-get install gcc-6 g++-6 -y 
  - sudo apt-get install cppcheck
  - sudo apt-get install valgrind
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 60 --slave /usr/bin/g++ g++ /usr/bin/g++-6

install:
  - echo `which $CC`
  - echo `which $CXX`
  - curl https://cmake.org/files/v3.6/cmake-3.6.1-Linux-x86_64.tar.gz | sudo tar -x -z --strip-components 1 -C /usr

script:
  - echo `which $CXX`
  - mkdir build && cd build;
    cmake -DCMAKE_CXX_COMPILER=$CXX ..
  - make example_examplelibrary_tests
  - make lab1_double_base_palindrome_tests
  - make lab2_array_2d_step1_tests
  - make lab2_array_2d_step2_tests
  - make lab2_array_2d_step3_tests
  - make lab2_array_2d_step4_tests
  - make lab2_simple_forward_list_step1_tests
  - make lab2_simple_forward_list_step2_tests
  - make lab2_simple_forward_list_step3_tests
  - make lab2_polybius_step1_tests
  - make lab2_polybius_step2_tests
  - make lab2_xor_cypher_breaker_tests
  - make lab3_smart_tree_step1_tests
  - make lab3_smart_tree_step2_tests
  - make lab3_smart_tree_step3_tests
  - make lab3_smart_tree_step4_tests
  - make lab3_smart_tree_step5_tests
  - make lab3_tiny_url_step1_tests
  - make lab3_tiny_url_step2_tests
  - make lab4_simple_template_engine_tests
  - make lab4_simple_template_engine_injection_tests
  - make lab4_simple_json_tests
  - make lab5_matrix_tests
  - make lab5_text_pool_tests
  - make lab6_word_counter_tests
  - make lab7_point3d_distance_tests
  - make lab7_point2d_distance_3d_tests
  - make lab7_point3d_cout_tests
  - make lab7_shapes_tests
  - make lab8_micro_dvd_correct_cases_tests
  - make lab8_micro_dvd_error_cases_tests
  - make lab8_movie_subtitles_tests
  - make lab8_sub_rip_correct_cases_tests
  - make lab8_sub_rip_error_cases_tests
  - make lab9_base_serializer_tests
  - make lab9_json_serializer_tests
  - make lab9_xml_serializer_tests
  - make lab10_schedule_tests
  - make lab10_scheduler_tests
  - make lab12_sequential_generator_tests
  - make lab12_teacher_hash_tests
  - make lab12_time_recorder_tests
  - make lab12_tree_preorder_tests
  - make lab12_tree_inorder_tests
  - make lab12_tree_postorder_tests
  - cd .. && echo 'RUNNING ALL COMPILED TESTS'
  - find build/tests/ -type f -name '*tests' -exec {} \;
  - echo 'RUNNING CPPCHECK STATIC ANALYSIS'
  - find -L example lab* -mindepth 1 -maxdepth 1 -type d | xargs cppcheck --check-config --xml --xml-version=2 --suppress=missingIncludeSystem --enable=warning,performance,information,style,portability 2> build/cppcheck-report.xml && cat build/cppcheck-report.xml
  - echo 'RUNNING VALGRIND MEMCHECK (it can take a while)'
  - find build/tests/ -type f -name '*tests' ! -regex '.*\(xor_cypher_breaker\|double_base_palindrome\)_tests' -exec valgrind --leak-check=full --show-mismatched-frees=yes --track-origins=yes {} \;


notifications:
  email: false
