//
// Created by Jan on 26.03.2018.
//

#ifndef JIMP_EXERCISES_SIMPLETEMPLATEENGINE_H
#define JIMP_EXERCISES_SIMPLETEMPLATEENGINE_H


class SimpleTemplateEngine {

};


#endif //JIMP_EXERCISES_SIMPLETEMPLATEENGINE_H
